{
  description = "unvX: a simple Home Manager configuration";

  inputs = {
    # Determinate Nix deprecates the default loading of nixpkgs, home-manager,
    # and flake-utils from the global flake registry, encouraging explicit input
    # specification instead.
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    nixpkgs,
    home-manager,
    flake-utils,
    ...
  }: let
    # unvX.nix is a file generated by the `install` script. unvX.nix contains
    # information about your unvX installation (e.g. your unvX module path on
    # your machine).
    unvX = import ./unvX.nix;
  in
    flake-utils.lib.eachSystem flake-utils.lib.allSystems (system: {
      # Specify your Home Manager profiles. Home Manager will by
      # default match first `$USER@$(hostname)`. If not found, it
      # will then default to `$USER`.

      packages.homeConfigurations = {
        "sulfyderz@Sulfyderz-MacBook-Pro.local" = home-manager.lib.homeManagerConfiguration {
          pkgs = nixpkgs.legacyPackages.${system};

          # Specify your Home Manager configurations.
          modules = [./host/Sulfyderz-MacBook-Pro/user/sulfyderz/home.nix];

          # Specify extra arguments to pass through your configurations.
          extraSpecialArgs = {inherit unvX;};
        };
      };
    });
}
