# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_stages = ["pre-commit"]
default_install_hook_types = [
  "pre-commit",
  "commit-msg"
  ]

[[repos]]
repo = "local"
hooks = [
  {
    id = "alejandra",
    name = "alejandra",
    description = "This hook checks Nix files with Alejandra.",
    entry = "alejandra -q",
    language = "system",
    files = '\.nix$'
  },
  {
    id = "shfmt",
    name = "shfmt",
    description = "This hook checks shell files with Shfmt.",
    entry = "shfmt -w",
    language = "system",
    types = ["shell"]
  },
  {
    id = "stylua",
    name = "stylua",
    description = "This hook checks Lua files with Stylua.",
    entry = "stylua",
    language = "system",
    files = '\.lua$'
  },
  {
    id = "yamlfmt",
    name = "yamlfmt",
    description = "This hook checks YAML files with Yamlfmt.",
    entry = "yamlfmt",
    language = "system",
    types = ["yaml"]
  },
  {
    id = "betterleaks-staged",
    name = "betterleaks (staged)",
    description = "This hook checks the existence of secrets in staged files.",
    entry = "betterleaks git --staged --redact --no-banner --verbose",
    language = "system",
    pass_filenames = false
  },
  {
    id = "betterleaks-history",
    name = "betterleaks (history)",
    description = "This hook checks the existence of secrets in git history.",
    entry = "betterleaks git --redact --no-banner --verbose",
    language = "system",
    pass_filenames = false
  }
]
