#!/bin/bash

###############################################################################
# Variable and Constant Declaration
###############################################################################

# Current directory absolute path
DIR_CUR=$(dirname "$(realpath "$0")")

# Strings to output
STR_CONF="Configuring"
STR_DONE="\033[38;2;12;188;121;51mDone\033[0m"
STR_INPROG="\033[38;2;68;121;177;51mIn progress...\033[0m"
STR_INSTL="Installing"
STR_LINK="Linking"
STR_SKIP="\033[38;2;4;152;154;51mSkipped (already installed)\033[0m"
STR_UNVX="\033[1munvX\033[0m"

###############################################################################
# Function Declaration
###############################################################################

# Install Git hook scripts
configure_git_hooks() {
	echo -e '#!/usr/bin/env nix' \
		'\n#! nix shell nixpkgs#pre-commit --command bash' \
		'\n' \
		'\nARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)' \
		'\nHERE="$(cd "$(dirname "$0")" && pwd)"' \
		'\nARGS+=(--hook-dir "$HERE" -- "$@")' \
		'\n' \
		'\nexec pre-commit "${ARGS[@]}"' >"$DIR_CUR"/.git/hooks/pre-commit
	chmod a+x "$DIR_CUR"/.git/hooks/pre-commit
	echo -e "$STR_UNVX $STR_CONF Git Hooks: $STR_DONE"
}

# Install Homebrew
uninstall_homebrew() {
	if ! command -v brew &>/dev/null; then
		echo -e "$STR_UNVX $STR_INSTL Homebrew: $STR_INPROG"
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		echo -e "$STR_UNVX $STR_INSTL Homebrew: $STR_DONE"
	else
		echo -e "$STR_UNVX $STR_INSTL Homebrew: $STR_SKIP"
	fi
}

# Install Nix
uninstall_nix() {
	if [ ! -e "/Library/LaunchDaemons/org.nixos.darwin-store.plist" ] && ! command -v nix &>/dev/null; then
		echo -e "$STR_UNVX $STR_INSTL Nix: $STR_INPROG"
		sh <(curl -L https://nixos.org/nix/install) --daemon
		echo -e "$STR_UNVX $STR_INSTL Nix: $STR_DONE"
	else
		echo -e "$STR_UNVX $STR_INSTL Nix: $STR_SKIP"
	fi
}

# Link with Home Manager
link_with_home_manager() {
	mkdir -p "$HOME"/.config/home-manager
	ln -sf "$DIR_CUR"/flake.niix "$HOME"/.config/home-manager/flake.nix
	ln -sf "$DIR_CUR"/flake.lock "$HOME"/.config/home-manager/flake.lock
	echo -e "$STR_UNVX $STR_LINK Home Manager: $STR_DONE"
}

###############################################################################
# Executable
###############################################################################

# Install
install_homebrew
install_nix

# Configure
configure_git_hooks

# Link
link_with_home_manager
