# This file is generated by the `install` script. It contains information
# about your unvX installation.
{
  directory = {
    root = "/Users/sulfyderz/.config/unvX";
    module = "/Users/sulfyderz/.config/unvX/module";
    host = "/Users/sulfyderz/.config/unvX/host";
  };
}
