"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugins
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Plugins are declared in `module/vim/default.nix` and symlinked into
" `pack/nix/start/`, where Vim's native package system loads them
set nocompatible
set packpath^=$HOME/.local/share/vim

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Options
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Backspace
set backspace=indent,eol,start

" Color activation
syntax enable
let g:molokai_original=1
colorscheme molokai

" Drop home message
set shortmess=I

" Encoding
set encoding=utf-8
set fileencoding=utf-8

" Indentation
set autoindent
set expandtab
set noerrorbells
set novisualbell
set number
set shiftwidth=2
set tabstop=2

" Line wrapping
set nowrap

" Mouse support
set mouse=a

" Netrw
let g:netrw_liststyle=3

" Search
set hlsearch
set ignorecase
set incsearch
set smartcase

" Settings
filetype on
filetype plugin on
filetype indent on

" Split windows
set splitbelow
set splitright

" Status line
set laststatus=2
set noshowmode
set showcmd
