name: ci
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3.21.5
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v14
      - name: Prek Hooks
        run: nix develop . -c prek run -a
