name: Code quality checker
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  code-quality-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Check format of Nix files (Alejandra)
        run: nix shell nixpkgs#alejandra --command alejandra -q -c .
      - name: Check format of shell files (shfmt)
        run: nix shell nixpkgs#shfmt --command shfmt -d .
      - name: Check format of Lua files (Stylua)
        run: nix shell nixpkgs#stylua --command stylua -c .
      - name: Check format of YAML files (yamlfmt)
        run: nix shell nixpkgs#yamlfmt --command yamlfmt -quiet -lint .
