name: Code quality checker
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  code-quality-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Check format of Nix files
        run: nix shell nixpkgs#alejandra --command alejandra -q -c .
      - name: Check format of shell files
        run: nix shell nixpkgs#shfmt --command shfmt -d .
      - name: Check format of Lua files
        run: nix shell nixpkgs#stylua --command stylua -c .
