name: Secret scanner
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  secret-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Scan secrets
        run: |
          nix shell nixpkgs#gitleaks --command gitleaks git --no-banner --verbose
          nix shell nixpkgs#gitleaks --command gitleaks dir --no-banner --verbose
